language: python

env:
  - DB_PORT=5555

services:
  - docker

before_install:
  - docker login -u "${DOCKER_HUB_LOGIN}" -p "${DOCKER_HUB_PASSWORD}"
  - docker-compose -f docker-compose.local.yaml pull
  - docker-compose -f docker-compose.local.yaml -f docker-compose.tests.yaml build

script:
  - docker-compose -f docker-compose.local.yaml -f docker-compose.tests.yaml up --abort-on-container-exit --exit-code-from testrunner