# Compose file to get a full deployment running.

version: '3'

volumes:
  database-data:
    driver: local

services:

  database:
    restart: always
    image: postgres:alpine
    volumes:
      - database-data:/var/lib/postgresql/data
    env_file:
      - database.env

  seed:
    image: callblocker:latest
    volumes:
      - database-data:/data
    command: ['sh', '/callblocker/bin/seed-db.sh']
    env_file:
      - database.env
    environment:
      - DJANGO_SETTINGS_MODULE=conf.settings.production.base
      - SEED_MARK_FOLDER=/data
      - LOAD_SAMPLE_DATA=${LOAD_SAMPLE_DATA:-False}
    depends_on:
      - 'database'
    links:
      - database

  # Actual backend server.
  backend:
    restart: always
    image: callblocker:latest
    ports:
      - '5000:${HOST_API_PORT:-5000}'
    env_file:
      - database.env
    environment:
      - DJANGO_SETTINGS_MODULE=conf.settings.production.server
      - HOST_API_ADDRESSES=${HOST_API_ADDRESSES:?HOST_API_ADDRESS is required}
      - HOST_API_PORT=${HOST_API_PORT:-5000}
      - MODEM_DEBUG=${MODEM_DEBUG:-False}
      - MODEM_USE_FAKE=${MODEM_USE_FAKE:-False}
    depends_on:
      - 'seed'
      - 'database'
    links:
      - database
    devices:
      - '${HOST_MODEM_DEVICE:?HOST_MODEM_DEVICE is required}:/dev/ttyACM0'
    
