version: '3'
services:
  postgres-dev:
    restart: always
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=devel
      - POSTGRES_PASSWORD=devel
      - POSTGRES_DB=blocker