version: '3'

volumes:
  database-data:
    driver: local

services:
  database:
    restart: always
    image: postgres:alpine
    volumes:
      - database-data:/var/lib/postgresql/data
    env_file:
      - database.env

  seed:
    image: callblocker:latest
    volumes:
      - database-data:/data
    command: ['/callblocker/bin/seed-db.sh']
    env_file:
      - database.env
    environment:
      - DJANGO_SETTINGS_MODULE=conf.settings.production.base
      - APP_FOLDER=/callblocker
    depends_on:
      - 'database'
    links:
      - database

  backend:
    restart: always
    image: callblocker:latest
    ports:
      - '5000:${HOST_API_PORT:-5000}'
    env_file:
      - database.env
    environment:
      - DJANGO_SETTINGS_MODULE=conf.settings.production.server
      - HOST_API_ADDRESS=${HOST_API_ADDRESS:?HOST_API_ADDRESS is required}
      - HOST_API_PORT=${HOST_API_PORT:-5000}
      - MODEM_DEBUG=${MODEM_DEBUG}
      - MODEM_USE_FAKE=${MODEM_USE_FAKE}
    depends_on:
      - 'seed'
      - 'database'
    links:
      - database
    devices:
      - '${HOST_MODEM_DEVICE:?HOST_MODEM_DEVICE is required}:/dev/ttyACM0'
