# Local dev. configuration for getting a Postgresql up and running.

version: '3'

services:

  database-dev:
    restart: always
    image: postgres:alpine
    ports:
      - "5432:${DB_PORT:-5432}"
    environment:
      - POSTGRES_USER=devel
      - POSTGRES_PASSWORD=devel
      - POSTGRES_DB=blocker