version: '3'
services:
  postgres:
    restart: always
    image: postgres:alpine
    environment:
      - POSTGRES_USER=blocker_user
      - POSTGRES_PASSWORD=blocker
      - POSTGRES_DB=blocker

  callblocker-seed:
    image: callblocker:latest
    command: ['/callblocker/bin/seed-db.sh']
    environment:
      - DJANGO_SETTINGS_MODULE=conf.settings.production.base
      - APP_FOLDER=/callblocker
      - DB_NAME=blocker
      - DB_USER=blocker_user
      - DB_PASSWORD=blocker
      - DB_HOST=postgres
      - DB_PORT=5432
    depends_on:
      - 'postgres'
    links:
      - postgres

  callblocker:
    restart: always
    image: callblocker:latest
    ports:
      - '5000:${HOST_API_PORT:-5000}'
    environment:
      - DJANGO_SETTINGS_MODULE=conf.settings.production.server
      - DB_NAME=blocker
      - DB_USER=blocker_user
      - DB_PASSWORD=blocker
      - DB_HOST=postgres
      - DB_PORT=5432
      - HOST_API_ADDRESS=${HOST_API_ADDRESS:?HOST_API_ADDRESS is required}
      - HOST_API_PORT=${HOST_API_PORT:-5000}
    depends_on:
      - 'callblocker-seed'
      - 'postgres'
    links:
      - postgres
    devices:
      - '${HOST_MODEM_DEVICE:?HOST_MODEM_DEVICE is required}:/dev/ttyACM0'
