# Generated by Django 2.2.1 on 2019-06-24 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_code', models.CharField(max_length=2)),
                ('number', models.CharField(max_length=9)),
                ('block', models.BooleanField()),
                ('date_inserted', models.DateTimeField()),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blocker.Source')),
            ],
            options={
                'unique_together': {('area_code', 'number')},
            },
        ),
        migrations.CreateModel(
            name='CallEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('blocked', models.BooleanField()),
                ('number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blocker.PhoneNumber')),
            ],
        ),
    ]
