# Generated by Django 2.2.3 on 2019-07-22 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Caller',
            fields=[
                ('full_number', models.CharField(max_length=28, primary_key=True, serialize=False)),
                ('area_code', models.CharField(max_length=8)),
                ('number', models.CharField(max_length=20)),
                ('date_inserted', models.DateTimeField(auto_now_add=True)),
                ('last_call', models.DateTimeField(auto_now_add=True)),
                ('block', models.BooleanField(default=False)),
                ('description', models.CharField(default='', max_length=200)),
                ('notes', models.TextField(blank=True, default='')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blocker.Source')),
            ],
        ),
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('blocked', models.BooleanField()),
                ('caller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blocker.Caller')),
            ],
        ),
    ]
