# Generated by Django 2.2.3 on 2019-08-03 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caller',
            name='last_call',
            field=models.DateTimeField(null=True),
        ),
    ]
